import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import { Inter } from "next/font/google";
import NavMenu from "./ui/NavMenu";
import "../public/globals.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
    title: "nutric",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NavMenu />
                <StackProvider app={stackServerApp}>
                    <StackTheme>
                        {children}
                    </StackTheme>
                </StackProvider>
            </body>
        </html>
    );
}